class ApiConstants {
  // static const String authbaseUrl = 'https://my-bible-backend.onrender.com';
  static const String authbaseUrl = 'http://10.0.2.2:5000';
  static const String loginEndpoint = '$authbaseUrl/api/auth/login';
  static const String registerEndpoint = '$authbaseUrl/api/auth/register';
  static const String user = '$authbaseUrl/api/users';
  static const String highlightsEndpoint = '$authbaseUrl/api/highlights';
  static const String accDetailsEndpoint = '$authbaseUrl/api/auth/profile';
  static const String bookMarkEndpoint = '$authbaseUrl/api/bookmarks';
  static const String directMessageEndpoint = '$authbaseUrl/api/direct';
  static const String group = '$authbaseUrl/api/groups';
  static const String event = '$authbaseUrl/api/events';
  static const String programItem = '$authbaseUrl/api/events/programItem';
  static const String addToGroup = '$authbaseUrl/api/groups/add';
  static const String groupMessages = '$authbaseUrl/api/groups/messages';
  static const String uploadImage = '$authbaseUrl/api/images/upload';
  static const String uploadService = '$authbaseUrl/api/services';
  static const String uploadSermon = '$authbaseUrl/api/services/sermons';
  static const String sermons = '$authbaseUrl/api/sermons';
  static const String devotions = '$authbaseUrl/api/devotions';
  static const String uploadDevotions = '$authbaseUrl/api/services/devotions';
  static const String saveImages = '$authbaseUrl/api/services/images';
  static const String services = '$authbaseUrl/api/services';
  static const String images = '$authbaseUrl/api/images';
  static const String passwordResetSendEndpoint =
      '$authbaseUrl/api/auth/password-reset/send';
  static const String passwordResetVerifyEndpoint =
      '$authbaseUrl/api/auth/password-reset/verify';
}

class Lists {
  static const books = [
    'Genesis',
    'Exodus',
    'Leviticus',
    'Numbers',
    'Deuteronomy',
    'Joshua',
    'Judges',
    'Ruth',
    '1 Samuel',
    '2 Samuel',
    '1 Kings',
    '2 Kings',
    '1 Chronicles',
    '2 Chronicles',
    'Ezra',
    'Nehemiah',
    'Esther',
    'Job',
    'Psalms',
    'Proverbs',
    'Ecclesiastes',
    'Song of Solomon',
    'Isaiah',
    'Jeremiah',
    'Lamentations',
    'Ezekiel',
    'Daniel',
    'Hosea',
    'Joel',
    'Amos',
    'Obadiah',
    'Jonah',
    'Micah',
    'Nahum',
    'Habakkuk',
    'Zephaniah',
    'Haggai',
    'Zechariah',
    'Malachi',
    'Matthew',
    'Mark',
    'Luke',
    'John',
    'Acts',
    'Romans',
    '1 Corinthians',
    '2 Corinthians',
    'Galatians',
    'Ephesians',
    'Philippians',
    'Colossians',
    '1 Thessalonians',
    '2 Thessalonians',
    '1 Timothy',
    '2 Timothy',
    'Titus',
    'Philemon',
    'Hebrews',
    'James',
    '1 Peter',
    '2 Peter',
    '1 John',
    '2 John',
    '3 John',
    'Jude',
    'Revelation'
  ];
  static const topics = [
    "Abundance",
    "Acceptance",
    "Accountability",
    "Addiction",
    "Advent 2021",
    "Adversity",
    "Alcohol",
    "Anger",
    "Anxiety",
    "Attitude",
    "Authority",
    "Backsliding",
    "Balance",
    "Baptism",
    "Beauty",
    "Being a Servant",
    "Being Born Again",
    "Being Faithful",
    "Being Humble",
    "Being like Christ",
    "Being Positive",
    "Being Thankful",
    "Believing God",
    "Betrayal",
    "Bitterness",
    "Blessings",
    "Boldness",
    "Bondage",
    "Bullying",
    "Calling",
    "Change",
    "Character",
    "Cheating",
    "Children",
    "Clarity",
    "Commitment",
    "Communion",
    "Community",
    "Compassion",
    "Compromise",
    "Confidence",
    "Confusion",
    "Contentment",
    "Control",
    "Conviction",
    "Counseling",
    "Courage",
    "Darkness",
    "Dating",
    "Death",
    "Debt",
    "Deception",
    "Deliverance",
    "Demons",
    "Destiny",
    "Determination",
    "Diligence",
    "Direction",
    "Discipline",
    "Discipleship",
    "Discouragement",
    "Disobedience",
    "Distractions",
    "Division",
    "Doubt",
    "Drinking",
    "Drunkenness",
    "Education",
    "Emotions",
    "Encouraging Others",
    "Envy",
    "Evangelism",
    "Excellence",
    "Expectation",
    "Failure",
    "Faith",
    "Family Love",
    "Family Unity",
    "Fasting",
    "Fathers",
    "Favor",
    "Fellowship",
    "Fighting",
    "Finances",
    "Flesh",
    "Focus",
    "Forgiveness",
    "Forgiveness of Sin",
    "Forgiving Yourself",
    "Foundation",
    "Freedom",
    "Friendship",
    "Generational Curses",
    "Gentleness",
    "Giving Offering",
    "Giving to the Poor",
    "Giving Up",
    "Gluttony",
    "God's Faithfulness",
    "God's Forgiveness",
    "God's Love",
    "God's Mercy",
    "God's Protection",
    "God's Provision",
    "Goodness",
    "Grace",
    "Gratitude",
    "Greed",
    "Happiness",
    "Hate",
    "Healing",
    "Healing a Broken Heart",
    "Health",
    "Helping Others",
    "Holiness",
    "Honesty",
    "Hopelessness",
    "Hospitality",
    "Humility",
    "Hunger",
    "Hypocrisy",
    "Identity",
    "Insecurity",
    "Integrity",
    "Joy",
    "Justice",
    "Kindness",
    "Leadership",
    "Light",
    "Listening",
    "Loneliness",
    "Love",
    "Loyalty",
    "Lust",
    "Lying",
    "Marriage",
    "Maturity",
    "Mercy",
    "Ministry",
    "Miracles",
    "Money",
    "Mothers",
    "New Beginnings",
    "Obedience",
    "Offense",
    "Overcoming Fear",
    "Parenting",
    "Patience",
    "Peace",
    "Persecution",
    "Perseverance",
    "Planning",
    "Pleasing God",
    "Praise",
    "Preparation",
    "Pride",
    "Procrastination",
    "Prosperity",
    "Protection",
    "Purity",
    "Purpose",
    "Putting God First",
    "Reconciliation",
    "Redemption",
    "Rejection",
    "Renewal",
    "Repentance",
    "Respect",
    "Responsibility",
    "Rest",
    "Restoration",
    "Resurrection",
    "Righteousness",
    "Salvation",
    "Sanctification",
    "Self Control",
    "Selfishness",
    "Serving God",
    "Shame",
    "Sin",
    "Sleep",
    "Speaking in Tongues",
    "Stewardship",
    "Stress",
    "Strongholds",
    "Surrender",
    "Temptation",
    "Thankfulness",
    "Thanksgiving",
    "The Flesh",
    "The Name of Jesus",
    "The Tongue",
    "Thoughts",
    "Tithing",
    "Transformation",
    "Trust",
    "Trusting God",
    "Truth",
    "Unity",
    "Victory",
    "Vision",
    "Wealth",
    "Wisdom",
    "Witnessing",
    "Worry",
    "Worship",
  ];
}
